const lau = [
    {
        name: "Lẩu mắm",
        description:
            "Lẩu mắm là cái tên đầu tiên trong danh sách những món lẩu được yêu thích ở vùng Tây Nam Bộ. Món lẩu này đặc trưng bởi mùi thơm nồng nàn và vị đậm đà của mắm cá linh, cá sặc,... Thêm vào đó là vị ngọt thanh của các loại rau xanh và nước lẩu chua ngọt hấp dẫn.",
        photo: "https://food.com.vn/upload/lau-mam.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-mam",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu gà lá giang",
        description:
            "Lẩu gà có lẽ là cái tên đã quá quen thuộc với mọi người. Tuy nhiên, lẩu gà lá giang lại là món ăn không phải ai cũng biết. Món lẩu này hấp dẫn bởi vị chua đặc trưng của lá giang mà không có bất kỳ bị chua nào có thể sánh được. Nó kết hợp với vị ngọt của thịt gà mang đến một nồi lẩu vô cùng hấp dẫn.",
        photo: "https://food.com.vn/upload/lau-ga-3.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-ga-la-giang",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu gà ớt hiểm",
        description:
            "Nếu bạn ăn được ớt cay thì đừng bỏ qua món lẩu gà ớt hiểm. Đây là một trong các món lẩu ngon dễ làm rất nhiều đấng mày râu yêu thích nhất. Ngoài vị cay của ớt hiểm, lẩu bò ăn có vị ngọt và thơm của kỷ tử, hoa hồi, quế,... Tất cả mang đến một nồi lẩu khó có thể cưỡng lại cho thời tiết ngày đông se lạnh.",
        photo: "https://food.com.vn/upload/lau-ga-ot-hiem-1.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-ga-ot-hiem",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu bò chấm chao",
        description:
            "Chao là một trong những loại gia vị của người dân miền Nam vô cùng quen thuộc. Và nếu như lẩu bò chấm với tương, xì dầu đã quá quen thuộc thì chúng ta nên đổi vị với lẩu bò Đà Lạt chấm chao. Với món lẩu này, chỉ cần ăn thử một lần bạn sẽ “nghiền” ngay.",
        photo: "https://food.com.vn/upload/lau-bo-cham-chao.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-bo-cham-chao",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu lươn chua cay",
        description:
            "Lẩu lươn cũng là một trong những món lẩu rất được yêu thích. Bởi thịt lươn vừa ngọt lại vừa nhiều chất dinh dưỡng. Khi vị ngọt của thịt lươn kết hợp với vị chua cay của nước lẩu lại càng trở nên hấp dẫn hơn. Còn về cách chế biến lẩu lươn chua cay, bạn có thể học tập công thức chế biến của lẩu ghẹ hoặc lẩu cua.",
        photo: "https://food.com.vn/upload/lau-luon-chua-cay.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-luon-chua-cay",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu dê",
        description:
            "Nhắc đến dê chắc chắn nhiều người chỉ biết đến các món truyền thống như: dê nướng, dê nấu nhựa mận đúng không nào? Vậy thì bạn đã bỏ qua món lẩu dê cực kỳ hấp dẫn rồi. Trong đó, thịt dê ngọt kết hợp với vị cay nồng của sả chắc chắn sẽ khiến nhiều người ấn tượng khó quên.",
        photo: "https://food.com.vn/upload/lau-de.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-de",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu chay",
        description:
            "Trong danh sách các món lẩu ngon dễ làm, chắc chắn bạn không thể bỏ qua lẩu chay. Đây là món lẩu dành riêng cho những người ăn kiêng cũng như ăn chay. Bạn sẽ không thể cảm thấy chán ngán với thịt cá mà trong khi đó nước lẩu vẫn đậm là thơm ngon. ",
        photo: "https://food.com.vn/upload/lau-chay.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-chay",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu cá hồi",
        description:
            "Mọi người thường chỉ biết đến cá hồi với món cá hồi nướng mà ít người thưởng thức lẩu cá hồi. Tuy nhiên, đây lại là món ăn vô cùng hấp dẫn và cực kỳ bổ dưỡng. Bởi cá hồi chứa nhiều omega 3 rất tốt cho tim mạch và mắt. ",
        photo: "https://food.com.vn/upload/lau-ca-hoi.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-ca-hoi",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu đuôi bò",
        description:
            "Trong danh sách các món lẩu ngon dễ làm tiếp theo không thể không nhắc đến lẩu đuôi bò. Đây là món lẩu có hương vị khác biệt hoàn toàn với món lẩu bò. Mặc dù vẫn có mùi và đặc trưng nhưng vị nước lẩu sẽ ngọt thanh hơn.thêm vào đó chúng ta có thể thưởng thức lẩu với rau má, rau cải đắng rất phù hợp. Đuôi bò vừa dai, vừa mềm mềm sẽ khiến mọi người ấn tượng khó quên.",
        photo: "https://food.com.vn/upload/lau-duoi-bo-1.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-djuoi-bo",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu nấm",
        description:
            "Đây cũng là một trong những món lẩu dành cho những người ăn chay. Trong đó, nguyên liệu chính là các loại nấm kết hợp với một chút vị chua của khóm, vị cay của ớt nên rất hấp dẫn. Vị giòn của nấm cũng là một đặc trưng vô cùng hấp dẫn của món lẩu này. Lưu ý, để nước lẩu ngọt hơn thì bạn nên xay nấm và pha cùng nước lẩu.",
        photo: "https://food.com.vn/upload/lau-nam.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-nam",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
    {
        name: "Lẩu cá thác lác",
        description:
            "Lẩu cá thác lác cũng là một cái tên không thể bỏ qua cho những ngày thời tiết se se lạnh. Nguyên liệu chính của món lẩu này là cá thác lác ngọt thanh kết hợp với vị đắng của khổ qua tạo nên nồi lẩu đậm đà hơn cả. Tuy nhiên, để nước lẩu ngon, ngoài xương cá thác lác bạn nên sử dụng xương heo cho ngọt nước.",
        photo: "https://food.com.vn/upload/lau-ca-thac-lac-1.jpg",
        category: "64b39030b02ce9e3d9dde600",
        slug: "Lau-ca-thac-lac",
        quantity: 20,
        priceSale: 89000,
        priceOrigin: 110000,
        soldOut: false,
        hidden: false,
        shopId: "64b38c56d453724bac20bc88",
    },
];
export default lau;
