const nhau = [
    {
        name: "Gà ta muối xông khói",
        description:
            "Đây được mệnh danh là vua của các món nhậu ngon đãi khách – đặc sản cực kỳ nổi tiếng tại Đà Nẵng.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/07/ga-hun-khoi.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Ga-ta-muoi-xong-khoi",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Giò heo muối xông khói",
        description:
            "Nhất nhì trong làng ẩm thực món nhậu ngon, không thể không điểm qua món chân giò muối xông khói rút xương.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/07/cach-che-bien-gio-heo-muoi.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Gio-heo-muoi-xong-khoi",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Bắp bò muối xông khói",
        description:
            "Bắp bò muối xông khói có nguồn gốc từ châu Âu, không chỉ giàu dinh dưỡng mà còn một món nhậu ngon siêu bén trên bàn tiệc.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/07/thit-bo-muoi-xong-khoi.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Bap-bo-muoi-xong-khoi",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Gỏi bò bóp thấu",
        description:
            "Gỏi bò bóp thấu là món ăn khai vị được sử dụng phổ biến tại các nhà hàng để kích thích vị giác cho thực khách.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/goi-bo-bop-thau.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Goi-bo-bop-thau",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Bò sốt me",
        description:
            "Bò sốt me là món nhậu ngon dễ làm, giàu dinh dưỡng, thích hợp cho các bữa tiệc cuối tuần, sinh nhật, liên hoan.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/bo-sot-me.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Bo-sot-me",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Gỏi tôm sống Thái Lan",
        description:
            "Gỏi tôm Thái hay còn gọi là tôm sống sốt Thái, gỏi tôm ngũ vị là một trong các món nhậu độc chiêu mang đậm phong cách ẩm thực xứ sở chùa vàng .",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/goi-tom-song-thai-lan.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Goi-tom-song-Thai-Lan",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Tôm sốt bơ tỏi",
        description:
            "Tôm là loại hải sản yêu thích của người Việt, thường xuyên xuất hiện trên những bàn tiệc đãi khách vào mỗi dịp cuối tuần.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/tom-sot-bo-toi.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Tom-sot-bo-toi",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Tôm hấp nước dừa",
        description:
            "Tôm hấp dừa hay còn gọi là tôm luộc nước dừa, tôm hấp trái dừa là món ăn ngon kết hợp hoàn hảo hai  loại nguyên liệu tốt cho sức khỏe.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/tom-hap-nuoc-dua.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Tom-hap-nuoc-dua",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Lòng nhồi tai heo",
        description:
            "Là món món nhậu ngon lạ miệng thay thế cho món dồi heo truyền thống. Với phần nhân là sự hòa quyện của giò sống thơm ngọt, tai heo giòn giòn, chút cay cay của ớt sừng và hương thơm của hành khô.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/long-nhoi-tai-heo.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Long-nhoi-tai-heo",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Lòng xào dưa chua",
        description:
            "Lòng non xào dưa chua giòn ngon sần sật, là mồi nhậu khoái khẩu của cánh mày râu khi uống bia, rượu.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/long-xao-dua-chua-1.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Long-xao-dua-chua",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Gỏi ngó sen tai heo",
        description:
            "Một món nhậu ngon yêu thích của người Nam bộ và cũng là món khai vị quen thuộc trong các nhà hàng tiệc cưới.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/goi-ngo-sen-tai-heo.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Goi-ngo-sen-tai-heo",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Ba chỉ lắc sả tắc",
        description:
            "Xoài lắc có, cóc lắc có nhưng ba chỉ lắc thì sao nhỉ ? Nghe kỳ kỳ phải không ? Nhưng không đâu, ba chỉ lắc xả tắc là món nhậu ngon từ thịt heo hoàn toàn có thực và đang rất “hot”.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/ba-chi-lac-sa-tac.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Ba-chi-lac-sa-tac",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Thịt heo cuộn nấm kim châm",
        description:
            "Nấm kim châm là thực phẩm bổ dưỡng chứa nhiều vitamin tốt cho sức khỏe, đặc biệt có hoạt chất phòng ngừa ung thư rất hiệu quả.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/ba-chi-cuon-nam-kim-cham.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Thit-heo-cuon-nam-kim-cham",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Chân gà chiên nước mắm tỏi ớt",
        description:
            "Món chân gà chiên nước mắm tỏi ớt là một biến thể thú vị của món chân gà chiên mắm truyền thống.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/chan-ga-chien-mam-toi-ot.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Chan-ga-chien-nuoc-mam-toi-ot",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Lòng gà trứng non cháy tỏi",
        description:
            "Nhiều thực khách rất kết, cực kỳ “bồ kết” cái món nhậu dân dã đồng quê mà ngon hết sảy mang tên trứng gà non cháy tỏi.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/long-ga-trung-non-chay-toi.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Long-ga-trung-non-chay-toi",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Cá hấp bia",
        description:
            "Khi Bạn đã cảm thấy ngán các món nhậu chiên, xào… chứa nhiều dầu mỡ thì món cá hấp bia là sự lựa chọn tuyệt vời để thay đổi khẩu vị.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/ca-hap-bia.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Ca-hap-bia",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Mực xào cần tây",
        description:
            "Những miếng mực trắng tinh, ngọt thịt, giòn giòn cùng cần tây xanh mướt, thơm nức, chắc chắn là món nhậu hải sản mà bạn không thể bỏ qua trên bàn tiệc đãi khách nhà mình.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/muc-xao-can-tay-1.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Muc-xao-can-tay",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Bạch tuộc hấp sả tắc",
        description:
            "Món bạch tuộc hấp sả tắc chuẩn đúng vị mồi nhậu bia cho các đấng mày râu. Bởi vậy, các chị em không nên bỏ lỡ món này mỗi khi nhà có tiệc nhé.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/bach-tuoc-hap-sa-tac.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Bach-tuoc-hap-sa-tac",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Đậu bắp xào tỏi",
        description:
            "Trong bàn tiệc đã có quá nhiều các món ăn giàu chất đạm thì đậu bắp xào tỏi là sự bổ sung chất xơ cần thiết, cân bằng hệ tiêu hóa, giòn giòn, thơm thơm, tỏi cay nức mũi.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/dau-bap-xao-toi.jpg",
        category: "6459f4d2453248061c861100",
        slug: "DJau-bap-xao-toi",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Nấm rơm xào tỏi",
        description:
            "Thêm một món nhậu bình dân ngon, dễ làm trên bàn tiệc. Món ăn không yêu cầu nhiều nguyên liệu phức tạp, thơm ngon không thua kém món mực xào tỏi.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/nam-rom-xao-toi.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Nam-rom-xao-toi",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Đậu phộng rang tỏi ớt",
        description:
            "Dù là tiệc lớn hay tiệc nhỏ, đậu phộng (lạc) cũng là món ăn “quốc dân” không thể thiếu trên bàn nhậu. Đậu phộng có thể thiếu bia nhưng bia thì không bao giờ có thể thiếu đậu phộng.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/dau-phong-rang-toi-ot.jpg",
        category: "6459f4d2453248061c861100",
        slug: "DJau-phong-rang-toi-ot",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Hến xúc bánh đa",
        description:
            "Hến xào sả ớt xúc bánh đa là món nhậu đặc sản nổi tiếng của người miền Trung. Thịt hến ngọt, thơm kết hợp cùng đậu phộng, mè, sả, ăn kèm với bánh đa nướng giòn rụm vô cùng hấp dẫn.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/hen-xuc-banh-da.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Hen-xuc-banh-dja",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Lẩu kim chi hải sản",
        description:
            "Trong bữa tiệc, lẩu là món ăn chính cuối cùng và để tăng thêm sự mới lạ cho khách dự tiệc, Bạn có thể chiêu đãi họ bằng món lẩu kim chi – món ăn truyền thống nổi tiếng của Hàn Quốc.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/lau-kim-chi-hai-san.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Lau-kim-chi-hai-san",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Lẩu gà ớt hiểm",
        description:
            "Thêm một món nhậu dễ làm tại nhà nổi tiếng của miền Tây, đang “làm mưa làm gió” trên các cộng đồng ăn uống (foody, diadiemanuong).",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/lau-ga-ot-hiem.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Lau-ga-ot-hiem",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Lẩu tôm Thái chua cay (Tom Yum)",
        description:
            "Nếu một ngày bạn tự hỏi: “nhậu món gì ngon ?”  thì lẩu tôm Thái (tomyum) sẽ là một gợi ý thú vị. Lẩu tôm Tomyum của Thái Lan từng được CNN bình chọn vào 8 món ăn hấp dẫn nhất thế giới.",
        photo: "https://zozozo.vn/wp-content/uploads/2019/11/lau-tom-thai-chua-cay.jpg",
        category: "6459f4d2453248061c861100",
        slug: "Lau-tom-Thai-chua-cay-(Tom-Yum)",
        quantity: 20,
        priceSale: 109000,
        priceOrigin: 140000,
        soldOut: false,
        hidden: false,
    },
];
export default nhau;
