const nuong = [
    {
        name: "Ba chỉ bò nướng",
        description:
            "Ba chỉ bò là phần đặc biệt thơm ngon và nhiều dinh dưỡng nhất, ba chỉ bò nướng không còn xa lạ với nhiều bạn trẻ khi món bò nướng BBQ rất phổ biến. Đây cũng một cơ hội kinh doanh không hề nhỏ cho các quán ăn hay nhà hàng.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/ba-chi-bo-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Ba-chi-bo-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Thịt nướng tảng",
        description:
            "Thịt nướng tảng mang lại hương vị đặc biệt, béo ngậy mỗi khi thưởng thức. Người ta thường dùng thịt lợn cùng với nhiều hương vị, gia vị tẩm ướp với nhiều công thức khác nhau, mang hương vị riêng của người đầu bếp.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/thit-nuong-tang.jpg",
        category: "6459f89a453248061c861106",
        slug: "Thit-nuong-tang",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Sườn bò nướng",
        description:
            "Phần sườn bò gồm phần thịt bọc lấy phần xương, khi thưởng thức chúng ta có thể cảm nhận được hương vị “ngon từ thịt ngọt từ xương” đúng chuẩn. Bạn có thể bổ xung ngay món ăn này vào trong thực đơn kinh doanh của bạn.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/suon-bo-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Suon-bo-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Lõi vai nướng",
        description:
            "Phần bắp bò đan xen giữa gân và thịt giúp chúng có sự đặc biệt riêng, lõi vai nướng ăn mềm và tan ngay trong miệng, hương vị lôi cuốn khiến người thưởng thức khó mà quên được.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/loi-vai-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Loi-vai-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Bò nướng lá lốt",
        description:
            "Chúng ta thường được ăn món thịt lợn băm cuốn lá lốt do mẹ nấu, nhưng hay thử đổi nguyên liệu sang thịt bò xem sao, cách làm cũng tương tự nhưng bạn sẽ bất ngờ khi thưởng thức nó đấy. 🙂",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/bo-la-not.jpg",
        category: "6459f89a453248061c861106",
        slug: "Bo-nuong-la-lot",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Đùi gà nướng",
        description:
            "Đùi gà nướng chúng ta có thể sử dụng cả phần bẹn hoặc chỉ dùng phần tỏi để chế biến, cách làm đơn giản nhất là tẩm ướp với ngũ vị hương và nướng ngay trên chính căn bếp nhà bạn để thưởng thức.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/dui-ga-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "DJui-ga-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Cánh gà nướng",
        description:
            "Cánh gà nướng chúng ta có thể dễ dàng bắt gặp ở nhiều quán ăn bụi ngoài vỉa hè, nguồn tiêu thụ cũng khá lớn mỗi ngày. Đây cũng là món ăn rất nên có trong thực đơn quán nướng của bạn.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/canh-ga-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Canh-ga-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Chân gà nướng",
        description:
            "Chân gà nướng là món ăn vặt yêu thích của nhiều bạn trẻ, combo chân gà cánh gà nướng luôn là tâm điểm của mỗi bữa tụ tập, trà tranh chém gió.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/chan-ga-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Chan-ga-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Mề gà nướng",
        description:
            "Mề gà nướng là món ăn còn khá mới với hương vị hấp dẫn không khác gì các món thịt nướng, cách làm và nguyên liệu cũng khá rẻ. Đây cũng là danh mục thực đơn đáng để đầu tư đối với các chủ quán ăn.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/me-ga-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Me-ga-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Món nướng mực",
        description:
            "Mực nướng muối ớt có hương vị cay nồng của ớt và vị ngọt dai của mực. Là một trong những món ăn khoái khẩu của chị em phụ nữ. Không chỉ vậy, còn là món yêu thích của đấng mày râu trên bàn nhậu.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/muc-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Mon-nuong-muc",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Rau bach tuộc nướng",
        description:
            "Bạch tuộc nướng hay hải sản nướng nói chung có hương vị đặc biết riêng, gia vị luôn cay nồng cùng màu sắc bắt mắt, nghĩ đến thôi là đã chảy nước miếng.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/rau-bach-tuoc-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Rau-bach-tuoc-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Đùi ếch nướng",
        description:
            "Đùi ếch nướng chỉ chế biến và lên đĩa chỉ trong 20p, với đùi ếch ta có thể chế biến thành các món nướng như: đùi ếch nướng muối ớt, đùi ếch nướng sa tế, đùi ếch nướng ống tre, đùi ếch nướng là nốt,..",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/dui-ech-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "DJui-ech-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Ba chỉ heo nướng",
        description:
            "Ba chỉ heo nướng, đây được coi như món ăn truyền thống đối với món nướng. Từng thớ thịt thơm ngon đan xen với thớ mỡ mang hương vị dai và béo ngậy. Đây chắc chắn sẽ là món ăn luôn có trong thực đơn nướng của mỗi nhà hàng.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/ba-chi-heo-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Ba-chi-heo-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Món nướng sườn heo",
        description:
            "Chắc chắn rồi, sườn heo lướng là quá tuyệt vời. Được tẩm ướp với nhiều hương liệu đặc biết giúp thịt mềm, thơm, ngậy. Chúng ta có thể nường cùng mật ong hoặc muối ớt, mỗi loại mang hương vị riêng nhưng khi ăn chắc chắn bạn sẽ thèm ăn nhiều lần nữa.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/suon-heo-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Mon-nuong-suon-heo",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
    {
        name: "Vú heo nướng",
        description:
            "Nầm nướng hay vú héo nướng là món ăn được nhiều người yêu thích, vú heo được tẩm ướp gia vị nướng lên có vị ngọt giai giòn sần sật cắn rất sướng. Chúng ta có thể chọn nhiều phương pháp chế biến và tẩm ướp, giá cả cũng rất phải chẳng.",
        photo: "https://h2tfood.vn/wp-content/uploads/2022/05/vu-heo-nuong.jpg",
        category: "6459f89a453248061c861106",
        slug: "Vu-heo-nuong",
        quantity: 20,
        priceSale: 99000,
        priceOrigin: 139000,
        soldOut: false,
        hidden: false,
    },
];

export default nuong;
