@baseUrl=http://localhost:8082/v1

POST {{baseUrl}}/role
Content-Type: application/json

{
    "name":"manager",
    "description":"level-1"
}

###
POST {{baseUrl}}/role
Content-Type: application/json

{
    "name":"waiter",
    "description":"level-2"
}

###
POST {{baseUrl}}/role
Content-Type: application/json

{
    "name":"chef",
    "description":"level-3"
}

###
POST {{baseUrl}}/role
Content-Type: application/json

{
    "name":"customer",
    "description":"level-4"
}

####

GET {{baseUrl}}/role
