@baseUrl=http://localhost:8082/v1

POST {{baseUrl}}/shop
Content-Type: application/json

{
    "name":"DuckDuck",
    "address":"Go Vap, HCM City",
    "logo":"https://cdn.dribbble.com/users/8762948/screenshots/16687667/duck2_1_.png"
}