@baseUrl=http://localhost:8081/v1

POST {{baseUrl}}/auth
Content-Type: application/json

{
    "email":"hung@gmail.com",
    "password":"1234567",
    "phone":"0987654321"
}

####

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"hung@gmail.com",
    "password":"1234567"
}